/**
 * Generic business-report Excel (.xlsx) renderer.
 *
 * Consumes the same flattened row stream as the PDF engine. Group bands are
 * indented labels in column A; money/mass cells are real numeric cells with
 * number formats (not strings), so totals stay usable in Excel. Number()
 * conversion happens only here, at the display boundary, after all Decimal
 * math is done. Server-side only.
 */
import * as XLSX from 'xlsx'
import type { ReportDocument } from '@/lib/reports/types'
import { flattenReportDocument } from '@/lib/reports/flatten'
import { formatDateSAST, formatDateTimeSAST, formatTimeSAST } from '@/lib/reports/format'

const NUMBER_FORMATS: Record<string, string> = {
  money: '#,##0.00',
  mass: '#,##0.00',
  qty: '#,##0.00',
  int: '#,##0',
}

export function generateBusinessReportXlsx(report: ReportDocument): ArrayBuffer {
  const flat = flattenReportDocument(report)
  // Photo columns have no meaningful spreadsheet representation — omit them.
  const cols = report.columns.filter((c) => !c.isImage)

  const aoa: (string | number | null)[][] = []

  // Title / params / company block
  aoa.push([report.title])
  if (report.subtitle) aoa.push([report.subtitle])
  aoa.push([
    `Selected Date Range From: ${formatDateSAST(report.params.from)}  To: ${formatDateSAST(report.params.to)}`,
  ])
  aoa.push([report.meta.company.name])
  aoa.push([`Print Date: ${formatDateTimeSAST(report.meta.generatedAt)}  |  Generated by: ${report.meta.generatedBy}`])
  aoa.push([])

  const headerRowIdx = aoa.length
  aoa.push(cols.map((c) => c.label))

  interface StyledCell { r: number; c: number; format?: string; bold?: boolean }
  const numericCells: StyledCell[] = []

  for (const row of flat) {
    const r = aoa.length
    const line: (string | number | null)[] = new Array(cols.length).fill(null)

    if (row.type === 'groupHeader') {
      line[0] = `${'  '.repeat(row.level)}${row.label ?? ''}${row.meta ? `  [${row.meta}]` : ''}`
      aoa.push(line)
      continue
    }

    const cells = row.cells ?? {}
    const isTotal = row.type === 'subtotal' || row.type === 'grandTotal'

    if (isTotal) {
      // Total label in the first column that carries no measure value
      line[0] = `${'  '.repeat(row.level)}${row.label ?? 'TOTAL:'}`
    }

    cols.forEach((col, cIdx) => {
      if (!Object.prototype.hasOwnProperty.call(cells, col.key)) return
      const raw = cells[col.key]
      if (raw === null || raw === undefined || raw === '') return

      const numFmt = col.format ? NUMBER_FORMATS[col.format] : undefined
      if (numFmt) {
        const n = Number(raw)
        if (Number.isFinite(n)) {
          line[cIdx] = n
          numericCells.push({ r, c: cIdx, format: numFmt })
          return
        }
      }
      if (col.format === 'date') { line[cIdx] = formatDateSAST(raw); return }
      if (col.format === 'time') { line[cIdx] = formatTimeSAST(raw); return }
      if (col.format === 'datetime') { line[cIdx] = formatDateTimeSAST(raw); return }
      line[cIdx] = raw
    })

    aoa.push(line)
  }

  const ws = XLSX.utils.aoa_to_sheet(aoa)

  // Number formats on numeric cells
  for (const cell of numericCells) {
    const ref = XLSX.utils.encode_cell({ r: cell.r, c: cell.c })
    const wsCell = ws[ref]
    if (wsCell && cell.format) wsCell.z = cell.format
  }

  // Column widths
  ws['!cols'] = cols.map((c, i) => ({
    wch: Math.max(c.excelWidth ?? 12, i === 0 ? 18 : 8),
  }))

  const wb = XLSX.utils.book_new()
  // Sheet names cap at 31 chars
  const sheetName = report.title.length > 31 ? report.title.slice(0, 28) + '…' : report.title
  XLSX.utils.book_append_sheet(wb, ws, sheetName.replace(/[\\/?*[\]:]/g, ' '))

  void headerRowIdx
  return XLSX.write(wb, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer
}
